micronaut:
  application:
    name: products
  server:
    port:
      9000
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    url: ${PRODUCTS_URL:`jdbc:postgresql://localhost:5432/products`}
    driverClassName: org.postgresql.Driver
    username: ${PRODUCTS_USER:postgres}
    password: 'root'
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
